
development:
  adapter: postgresql
  encoding: unicode
  database: coach
  pool: 5
  username: c240
  password: password


test:
  adapter: postgresql
  encoding: unicode
  database: coach
  pool: 5
  username: c240
  password: password


production:
  adapter: postgresql
  encoding: unicode
  database: coach
  pool: 5
  username: c240
  password: password
